#!/bin/sh

APP_NAME=<WEB_APP_NAME>
RESOURCE_GROUP=<RESOURCE_GROUP_NAME>
APP_PLAN=<APP_SERVICE_PLAN_NAME>
#CONTAINER_IMAGE=yoichikawasaki/mean-demo:0.0.1
CONTAINER_IMAGE=<REGISTRY_URL>/<CONTAINER_IMAGE:TAG>

# Create Web App for Container
az webapp create \
  -n $APP_NAME \
  -g $RESOURCE_GROUP \
  -p $APP_PLAN \
  -i $CONTAINER_IMAGE
